export const CASE_CATEGORIES = [
  'Cardiac Arrest',
  'Difficult Intubation',
  'COPD Exacerbation',
  'Septic Shock',
  'Anaphylaxis',
  'Hypovolemic Shock',
  'Respiratory Failure',
  'Pulmonary Embolism',
  'Acute Myocardial Infarction',
  'Stroke',
  'Traumatic Brain Injury',
  'Spinal Cord Injury',
  'Burn Management',
  'Pediatric Emergency',
  'Obstetric Emergency',
  'Regional Anesthesia Complication',
  'Malignant Hyperthermia',
  'Airway Obstruction',
  'Aspiration',
  'Drug Overdose',
  'Hypothermia',
  'Hyperthermia',
  'Electrolyte Imbalance',
  'Endocrine Emergency',
  'Neurological Emergency',
  'Other',
] as const;

export type CaseCategory = (typeof CASE_CATEGORIES)[number];
