name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Test
        env:
          NODE_ENV: test
          NEXTAUTH_SECRET: test-secret-key-test-secret-key-test
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: file:./prisma/test.db
        run: pnpm test
      - name: Build
        env:
          NEXTAUTH_SECRET: test-secret-key-test-secret-key-test
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: file:./prisma/dev.db
        run: pnpm build
